events:
  - Logged In
  - Viewed Dashboard
  - Activated Email
  - First Time Pro
  - First Time Premium
  - Generated Calculator Report
  - Hard Money Lead Submitted
  - Real Estate Agent Lead Submitted
