events:
  - Activated Email
  - Clicked Matched Vendor Contact
  - Clicked Matched Vendor Contact all
  - Clicked Vendor Matching Resource
  - Completed Vendor Matching Step
  - First Time Premium
  - First Time Pro
  - Generated Calculator Report
  - Hard Money Lead Submitted
  - Logged In
  - Real Estate Agent Lead Submitted
  - Registered for Webinar
  - Viewed Dashboard
