events:
  - Logged In
  - Viewed Dashboard
  - Activated Email
  - First Time Pro
  - First Time Premium
  - Generated Calculator Report
  - Hard Money Lead Submitted
  - Real Estate Agent Lead Submitted
  - Clicked Matched Vendor Contact all
  - Clicked Matched Vendor Contact
  - Completed Vendor Matching Step
  - Clicked Vendor Matching Resource
